apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend
spec:
  replicas: 2  # Scale theo nhu cầu
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/manhndvinhyen/ci-cd:latest  # Thay bằng image thật từ CI
        ports:
        - containerPort: 3000  # Port của server.js (thay nếu khác)
        envFrom:
        - configMapRef:
            name: app-config  # Reference configmap
        - secretRef:
            name: app-secret  # Nếu có secret cho app